name: 'public-company-overview'
version: 1.0.0

profile: 'public-company-overview'
target-path: 'target'

models:
  public-company-overview:
    staging:
      +materialized: incremental
    intermediate:
      +materialized: incremental
    marts:
      +materialized: table

