name: 'public_company_overview_dbt'
version: 1.0.0

profile: 'public_company_overview'
target-path: 'target'

vars:
  past_proof_date: '1900-01-01'

models:
  public_company_overview_dbt:
    staging:
      +materialized: incremental
    intermediate:
      +materialized: incremental
    marts:
      +materialized: table

