public_company_overview:
  outputs:
    dev:
      dataset: pco_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      priority: interactive
      project: public-company-overview
      threads: 1
      type: bigquery
  target: dev